global:
  domain: argocd.homelab

configs:
  params:
    server.insecure: true  # TLS terminated at Traefik

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: argocd.homelab
