apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: infra
spec:
  project: default
  source:
    repoURL: https://github.com/adi-amatdev/homelab
    targetRevision: HEAD
    path: k8s/cloud/adguard
  destination:
    server: https://kubernetes.default.svc
    namespace: cloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
