apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          args:
            - --appendonly
            - yes
            - --save
            - "60"
            - "1"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          hostPath:
            path: /home/aadi/store/redis-data
            type: DirectoryOrCreate
