apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <your-app>
  namespace: infra
spec:
  project: default
  source:
    repoURL: https://github.com/adi-amatdev/homelab
    targetRevision: HEAD
    path: ai/<your-app>
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
