globalArguments:
  - "--global.sendanonymoususage=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"

ports:
  web:
    port: 80
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    exposedPort: 443
    protocol: TCP
  private:
    port: 8081
    exposedPort: 8081
    expose:
      default: true
    protocol: TCP

ingressRoute:
  dashboard:
    enabled: true
    entryPoints: ["web"]
    matchRule: "Host(`traefik.homelab`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"

service:
  type: LoadBalancer

logs:
  general:
    level: INFO

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
