apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <your-app>
  namespace: infra
spec:
  project: default
  source:
    repoURL: https://github.com/adi-amatdev/homelab
    targetRevision: HEAD
    path: k8s/<apps|cloud|ai>/<your-app>
  destination:
    server: https://kubernetes.default.svc
    namespace: <namespace>            # apps | cloud | ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
