apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: infra
spec:
  project: default
  sources:
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: "2.17.2"
      releaseName: sealed-secrets
      helm:
        values: |
          {}
    - repoURL: https://github.com/adi-amatdev/homelab
      targetRevision: HEAD
      path: k8s/platform/sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
