apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: infra
spec:
  project: default
  source:
    repoURL: https://github.com/adi-amatdev/homelab
    targetRevision: HEAD
    path: k8s/platform/sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
