apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: infra
spec:
  project: default
  sources:
    - repoURL: https://github.com/adi-amatdev/homelab
      targetRevision: HEAD
      ref: values
    - repoURL: https://helm.traefik.io/traefik
      chart: traefik
      targetRevision: 34.4.1
      helm:
        valueFiles:
          - $values/platform/traefik/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
